[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "estregg"
version = "1.0.7"
description = "ESTREGG Space Exploration Terminal Game"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "windows-curses; platform_system == 'Windows'",
]

[project.scripts]
estregg = "estregg:main"
